### ISSUE TITLE
Test Specific Transport

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#11]

**Comment by DavidAntaramian** [comment]
This may not actually be necessary after all

**Comment by binarylogic** [comment]
Can you elaborate?

**Comment by DavidAntaramian** [comment]
I've been going back and forth on the best way to do this. The idea behind a test specific transport is that we would have a transport that is specifically dedicated to receiving lines and then comparing them against expected lines. Similar to how Bypass works for HTTP requests
