### ISSUE TITLE
Include Timber API errors and retry count as headers in the HTTP client

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#133]
If the HTTP client fails a request, we'll get an error from the Timber service. I'd like to record this, as well as the retry count, and include it in subsequent retries so that we can report on it. Ideally these would be headers.

**Comment by DavidAntaramian** [comment]
We have internal metrics that allow us to track this information now. I don't believe that there's any need to have the client libraries record this information.

@binarylogic Please reopen this if you don't agree
