### ISSUE TITLE
Failing with Phoenix 1.3.0-rc1

### ISSUE THREAD

**Issue by CadmusRhys** [timberio/timber-elixir#144]
When trying to add timber to my Phoenix umbrella application it fails due to;

timber (version 2.1.6) requires ~> 1.2 *

Can you add 1.3.0-rc1 to the version constraints?

**Comment by binarylogic** [comment]
Yep, added via https://github.com/timberio/timber-elixir/commit/a311d8d782489a9938f7c7df7cc79015a4d9c2c0 . For now if you want to update the `timber` dependency to:

```
{:timber, github: "timberio/timber-elixir"}
```

That should resolve this. We plan to cut a new release this week.

**Comment by binarylogic** [comment]
Actually, I decided to go ahead and release a new version. `mix deps.update timber` should do it.
