### ISSUE TITLE
Allow for comments / feedback regardless of rating

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#147]
Capture comments regardless of the installer rating.

**Comment by DavidAntaramian** [comment]
Currently, users can provide a comment if they rank the installation process with `1`, `2`, or `3`; when a user ranks as `4` or `5`, there is no prompt for a comment.

https://github.com/timberio/timber-elixir/blob/98c42a9dbaf6bff1e165f27809398e76ee88784a/lib/mix/tasks/timber/install.ex#L282-L323
