### ISSUE TITLE
Installer config changes can override other config, prompt to customize

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#148]
While we can't really merge the config, we got feedback that it would be helpful to mention they can further customize the config.

**Comment by DavidAntaramian** [comment]
I'm not sure what this issue means

**Comment by binarylogic** [comment]
I should have been more clear, pretty sure I created this in haste. I was referring to the configuration block the installer automatically appends to the user's `config.exs` file:

```elixir
config :logger,
  backends: [Timber.LoggerBackends.HTTP],
  utc_log: true
```

This has the potential to override any previous `:logger` settings they've set.

**Comment by DavidAntaramian** [comment]
That makes sense. To be clear for other readers, this happens during the installation process. Also, we should be containing this to the `timber.exs` configuration file, correct?

So it would be good to add a note to the installer output saying something like:

```
As part of the installation, the configuration in config/timber.exs contains the following:

  config :logger,
    backends: [Timber.LoggerBackends.HTTP],
    utc_log: true

This will override configuration you already have for :logger. If you already
have custom backends, we suggest you review these changes and merge
them into your existing configuration to prevent surprises.
```
