### ISSUE TITLE
Application won't start on my production server after setting up Timber

### ISSUE THREAD

**Issue by naps62** [timberio/timber-elixir#164]
I'm unable to get this working in production so far. To be clear, I fully believe this is my fault, but need help figuring out the issue.

I'm using an Umbrella app, and the setup didn't seem to be fully prepared for that, so I had to make some adjustments manually. That could be the origin of the issue.

Here's my `config/timber.exs`:

```
use Mix.Config

# Update the instrumenters so that we can structure Phoenix logs
config :mse_web, Mse.Web.Endpoint,
  instrumenters: [Timber.Integrations.PhoenixInstrumenter]

# Structure Ecto logs
config :db, DB.Repo,
  loggers: [{Timber.Integrations.EctoLogger, :log, [:info]}]

# Use Timber as the logger backend
# Feel free to add additional backends if you want to send you logs to multiple devices.
# Deliver logs via HTTP to the Timber API by using the Timber HTTP backend.
config :logger,
  backends: [Timber.LoggerBackends.HTTP],
  utc_log: true

# For the following environments, do not log to the Timber service. Instead, log to STDOUT
# and format the logs properly so they are human readable.
environments_to_exclude = [:dev, :test]
if Enum.member?(environments_to_exclude, Mix.env()) do
  # Fall back to the default `:console` backend with the Timber custom formatter
  config :logger,
    backends: [:console],
    utc_log: true

  config :logger, :console,
    format: {Timber.Formatter, :format},
    metadata: [:timber_context, :event, :application, :file, :function, :line, :module]

  config :timber, Timber.Formatter,
    colorize: true,
    format: :logfmt,
    print_timestamps: true,
    print_log_level: true,
    print_metadata: false # turn this on to view the additiional metadata
end

# Need help?
# Email us: support@timber.io
# Or, file an issue: https://github.com/timberio/timber-elixir/issues
```

The thing I had to change there was `config :db, DB.Repo`, which originally was `config :mse_web, DB.Repo` (:db is a sub-app of the umbrella project, where I keep the repo among other things)

Locally, I'm able to run the server in production mode (with `MIX_ENV=prod`) and see the logs showing up on timber.io.

I can even test it in a simpler way:

```
MIX_ENV=prod iex -S mix
> require Logger
> Logger.info("teste")
:ok
```
This also shows up on the dashboard

However, when deploying this to my actual production server (running on docker via docker-compose), I get the following crash on startup:

```
web_1    | =INFO REPORT==== 20-Jun-2017::20:38:15 ===
web_1    |     application: logger
web_1    |     exited: {{shutdown,
web_1    |               {failed_to_start_child,'Elixir.Logger.Watcher',
web_1    |                {'EXIT',
web_1    |                 {{badmatch,
web_1    |                   {error,
web_1    |                    {{{case_clause,
web_1    |                       {'EXIT',
web_1    |                        {undef,
web_1    |                         [{'Elixir.Timber.LoggerBackends.HTTP',init,
web_1    |                           ['Elixir.Timber.LoggerBackends.HTTP'],
web_1    |                           []},
web_1    |                          {gen_event,server_add_handler,4,
web_1    |                           [{file,"gen_event.erl"},{line,429}]},
web_1    |                          {gen_event,handle_msg,5,
web_1    |                           [{file,"gen_event.erl"},{line,274}]},
web_1    |                          {proc_lib,init_p_do_apply,3,
web_1    |                           [{file,"proc_lib.erl"},{line,247}]}]}}},
web_1    |                      [{'Elixir.Logger.Watcher',do_init,3,
web_1    |                        [{file,"lib/logger/watcher.ex"},{line,78}]},
web_1    |                       {gen_server,init_it,6,
web_1    |                        [{file,"gen_server.erl"},{line,328}]},
web_1    |                       {proc_lib,init_p_do_apply,3,
web_1    |                        [{file,"proc_lib.erl"},{line,247}]}]},
web_1    |                     {child,undefined,
web_1    |                      {'Elixir.Logger.Watcher',
web_1    |                       {'Elixir.Logger','Elixir.Timber.LoggerBackends.HTTP'}},
web_1    |                      {'Elixir.Logger.Watcher',watcher,
web_1    |                       ['Elixir.Logger','Elixir.Timber.LoggerBackends.HTTP',
web_1    |                        'Elixir.Timber.LoggerBackends.HTTP']},
web_1    |                      transient,5000,worker,
web_1    |                      ['Elixir.Logger.Watcher']}}}},
web_1    |                  [{'Elixir.Logger.Watcher','-start_link/3-fun-0-',2,
web_1    |                    [{file,"lib/logger/watcher.ex"},{line,16}]},
web_1    |                   {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
web_1    |                    [{file,"lib/enum.ex"},{line,1755}]},
web_1    |                   {'Elixir.Logger.Watcher',start_link,3,
web_1    |                    [{file,"lib/logger/watcher.ex"},{line,15}]},
web_1    |                   {supervisor,do_start_child,2,
web_1    |                    [{file,"supervisor.erl"},{line,365}]},
web_1    |                   {supervisor,start_children,3,
web_1    |                    [{file,"supervisor.erl"},{line,348}]},
web_1    |                   {supervisor,init_children,2,
web_1    |                    [{file,"supervisor.erl"},{line,314}]},
web_1    |                   {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
web_1    |                   {proc_lib,init_p_do_apply,3,
web_1    |                    [{file,"proc_lib.erl"},{line,247}]}]}}}},
web_1    |              {'Elixir.Logger.App',start,[normal,[]]}}
web_1    |     type: permanent
```

and the application refuses to start

Any tips on what this might be, or where to start debugging this?

**Comment by DavidAntaramian** [comment]
Hey @naps62!

To start off, could you give me the following information:

 - Elixir version
 - Erlang version
 - Timber version

**Comment by DavidAntaramian** [comment]
On a quick glance, it seems that when `Logger` boots, it tries to initialize the relevant backends that have been defined. It tried to initialize the Timber HTTP backend, but according to the error report shown, the initialization function is undefined. What this suggests to me is that the module (and most likely the entire library) is _not_ being compiled in `prod`.

**Comment by naps62** [comment]
@DavidAntaramian sure thing

On my development environment:
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.4) - press Ctrl+C to exit (type h() ENTER for help)
```

On the docker container where the app is compiled & executed:
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
```

Timber version is set to 2.2.1 on `mix.lock`

**Comment by DavidAntaramian** [comment]
My current working hypothesis is that you only inserted the dependency into the top-level `mix.exs`, but you did not insert it into the `mix.exs` of any component applications. Is that correct?

**Comment by naps62** [comment]
@DavidAntaramian your first comment tipped me off. I was about to say it still didn't solve it, but I just found it out

Timber was indeed missing from `extra_applications`. I'm not sure if the installer was suposed to do that for me, but since this I installed this at the root of an umbrella app, I guess it couldn't do that anyway

So I added a dedicated sub-app for logging, and added timber directly to it. I was about to say that didn't work as well, but then I noticed I had to add it as a dependency to the sub-application, so that it would start first.

While this was my fault, it leads me to think your docs should cover installations for umbrella applications, particularly these kinds of caveats?

Anyway, thanks for all the help :)

**Comment by DavidAntaramian** [comment]
@naps62 We can probably add documentation somewhere, but this has more to do with umbrella application documentation as a whole rather than a Timber-specific issue. Since Timber is a runtime dependency, it needs to be declared as a dependency for each application that depends on it (at least `:db` and `:mse_web` in your case). Mix does not include dependencies listed in the top-level umbrella application `mix.exs` as build artifacts; that list is for convenience tooling during the build process. That was why its modules were undefined when you tried to run it in a production setting. Timber should also _not_ be added to the `extra_applications` list; Mix should be able to resolve its inclusion in the application list without that.

**Comment by naps62** [comment]
@DavidAntaramian yes, I understand that :)

This was mostly a fact of me not being very experienced with Elixir, and particularly with umbrella apps.

Oh well, you leave and you learn

**Comment by DavidAntaramian** [comment]
@naps62 Yeah, I understand. The story regarding umbrella applications is still evolving, so it's difficult to give good guidance when what's good today might not be the best practice two days from now.
