### ISSUE TITLE
Better control over `dt` in the log line format

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#166]
In certain environments it's preferable to preferable to prefix or remove the dt all together:

1. If you're using our agent, prefixing the line with the `dt` is preferred.
2. If you're using syslog or Heroku, you might want to drop the `dt` entirely.

**Comment by DavidAntaramian** [comment]
@binarylogic Why do we want to drop the `dt`? The `dt` internally can still be more accurate than the one assigned by an external system.
