### ISSUE TITLE
Fix broken links throughout documentation

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#193]
The documentation has a number of links that end in 404. These need to be removed or pointed to the correct place.

**Comment by zsherman** [comment]
![Screenshot 2017-08-02 10.32.58.png](https://zube.io/files/timberio/7707be3134f2183a22e22e8c16ae0313.png)

**Comment by binarylogic** [comment]
I ran a dead link scanner over the entire site and fixed all broken links.
