### ISSUE TITLE
Allow a global context to be set

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#196]
The global context will be merged into every log line's context before it is sent to the server.

**Comment by binarylogic** [comment]
I'm thinking we use `Agent`, like you suggested, and the API would be:

```elixir
Timber.add_context(%{...}, global: true)
```

**Comment by DavidAntaramian** [comment]
I think I'd actually want to use `:ets` for this, based on further analysis. `:ets` will offer us a greater read/write throughput than Agent will.

**Comment by ksheurs** [comment]
Is there a rough time estimate for this?

**Comment by net** [comment]
🎉

**Comment by ksheurs** [comment]
Is there a plan to release a new version with this change or will this get grouped into a larger version in the future?

**Comment by DavidAntaramian** [comment]
@ksheurs I'm hoping to release this in a few days. I'm working on #253 and #258 which I'd like to package into the same release.
