### ISSUE TITLE
Allow user to log only long-running queries

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#197]
I was asked if it was possible to log only queries that took longer than 1 second to run. I'm not sure how useful this feature will be to everyone. What I would propose is that we allow the user to configure a specific number of milliseconds (defaulting to `0`). If the query time takes longer than that, we log it. This keeps existing functionality while extending it to allow for what the user has requested.

**Comment by Trevoke** [comment]
My original thought was an assumption that every Ecto query would come through the Timber logger, but that maybe additional filtering hooks could be added in some way.

I asked for this feature for two reasons:

1. I have a recurring query that is taking up a lot of log space and I don't need to see it unless something is wrong with it
2. If we're logging through Ecto, then Timber might well take over some of the job of the postgres (or other database) logs, and one of the most useful features I've ever used was precisely "log query if it took longer than X milliseconds".

https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html
http://community.jaspersoft.com/wiki/logging-long-running-queries-postgres-and-mysql-databases

Timber is a fantastically useful aggregation tool, but .. Maybe it aggregates TOO MUCH! :D

**Comment by DavidAntaramian** [comment]
Yep. So, basically what happens is that Timber's Ecto integration is registered as a callback for Ecto's log function. The log function gets called after a query completes with various statistical information. We then decide what we do with this information (in our case, we log it). The logic is actually very simple: https://github.com/timberio/timber-elixir/blob/master/lib/timber/integrations/ecto_logger.ex#L71

And yes, we have heard complaints about noisiness with Ecto logs. We want to strike the right balance

**Comment by binarylogic** [comment]
Hi @Trevoke, if you update to [`2.5.0`](https://github.com/timberio/timber-elixir/releases/tag/v2.5.0) you'll get structured `Phoenix.Channel` events, as well as the option to specify a query threshold. If you view [the release](https://github.com/timberio/timber-elixir/releases/tag/v2.5.0) you'll notice a simple change needed to migrate to `2.5.0`. This disables the default Phoenix channel logging so you don't see them twice in your logs. Let us know if you have any questions.

**Comment by Trevoke** [comment]
Ooh, I'm looking forward to trying this out. 
I don't fully grok channels yet, but isn't there a `handle_out` as well? Is that not something we'd need to also disable the Phoenix logging for?

**Comment by binarylogic** [comment]
Great! No, that doesn't appear to be an option. Notice [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel.ex#L254-L259) they mention only logging the `join` and `channel_in` events.

**Comment by Trevoke** [comment]
That's fascinating; thanks for the link to the source :)

I guess the Phoenix framework doesn't yet allow redirecting of its own
logging work out to custom loggers like Timber? If so, does Timber intend
to work with the Phoenix team to make that possible?

**Comment by DavidAntaramian** [comment]
@Trevoke 

> I guess the Phoenix framework doesn't yet allow redirecting of its own logging work out to custom loggers like Timber?

I'm not sure what you mean here. The majority of Phoenix's default logging is for startup errors (e..g, "port already in use"). Otherwise, Phoenix implements logging using the same hooks as we do. [`Phoenix.Logger`](https://github.com/phoenixframework/phoenix/blob/v1.3.0/lib/phoenix/logger.ex) is the default instrumentation module.

**Comment by Trevoke** [comment]
Well, according to the documentation to configure Timber, I need to turn off Phoenix logging for controllers and channels (e.g. `use Phoenix.Channel, logging: false`). That's odd. I would expect that I'm redirecting the framework's logging to Timber. That's what I mean.

**Comment by DavidAntaramian** [comment]
@Trevoke Ah, OK. So what's happening is this:

  - Phoenix installs its default instrumentation handler, `Phoenix.Logger` by default
  - As the end-user, you also specify `Timber.Integrations.PhoenixInstrumenter` which is our implementation of the endpoint instrumentation
  - When Phoenix handles a instrumented event (`:phoenix_controller_call`, `:phoenix_controller_render`, `:phoenix_channel_join`, `:phoenix_channel_receive`) it will call _each_ instrumenter in turn with metadata about the event
  - When you specify `use Phoenix.Channel, log_join: false, log_handle_in: false`, Phoenix will set the  private properties on the socket for `:log_join` and `:log_handle_in`
  - When `Phoenix.Logger` receives the `:phoenix_channel_join` or `:phoenix_channel_receive` event, the private [`channel_log/3`](https://github.com/phoenixframework/phoenix/blob/v1.3.0/lib/phoenix/logger.ex#L94) function is used to determine whether or not to log something based on those fields
  - The Timber instrumenter ignores those fields

So, you're not redirecting Phoenix logs to Timber. Phoenix is sending the instrumentation event to _both_ itself and Timber, but you tell Phoenix to ignore those events in its own implementation. So only Timber ends up producing logs.

**Comment by Trevoke** [comment]
Ah... Interesting, thanks! I'm getting a better sense of why the changes are made inside the `web.ex` file now.
