### ISSUE TITLE
User joins channel, user sends message: "Validation Failed"

### ISSUE THREAD

**Issue by Trevoke** [timberio/timber-elixir#202]
I'm using Timber 2.5.2 for Elixir with Phoenix 1.3.

This is one of those things where I'll need your help because I don't know if it's on our side or your side, and I don't know enough to really give you useful information. In the logs, we properly see the log lines as enhanced by Timber, but Timber's validation fails and I don't know what that means...

**Comment by Trevoke** [comment]
(in addition, `is:timber.validation_error`, which is the filter that shows up when I click on the "Validation Failed" message, seems to have a defect, it indicates "no results"...)

**Comment by binarylogic** [comment]
Closing. Notified @Trevoke external of Github last week of the resolution.

**Comment by felippenardi** [comment]
@binarylogic What was the resolution? I'm running into the same problem.

**Comment by binarylogic** [comment]
Hi @felippenardi, we resolved the issue on our end, it should no longer be relevant. I'm going to look into why you're experiencing this now.

**Comment by felippenardi** [comment]
Thanks @binarylogic! Do you need anything from me?

**Comment by felippenardi** [comment]
@binarylogic Still waiting on this

**Comment by binarylogic** [comment]
Hey @felippenardi, apologies for the delay. The holidays + vacation pushed things back a little. I will put this in the sprint for next week.

**Comment by DavidAntaramian** [comment]
Is there any update on this issue?

**Comment by DavidAntaramian** [comment]
This may be better moved to a support ticket if it's no longer related to the library specifically.

**Comment by felippenardi** [comment]
This is related to the library, something is wrong and I can't get my logs correctly.

**Comment by binarylogic** [comment]
Just noting, we've since removed the entire concept of a schema / validation within the Timber API. You should never see a validation error going forward. As a result, this should be resolved. Please let us know if you notice anything else.
