### ISSUE TITLE
Supporting Hackey 1.9.0

### ISSUE THREAD

**Issue by cuongtnx** [timberio/timber-elixir#203]
Hi,

Hackney has released 1.9.0, which doesn't really do anything differently from 1.8.6 (fixing typo type of commits), rather just to have a more rounded number. 

Will this be supported in Timber soon?

**Comment by DavidAntaramian** [comment]
@cuongtnx We've had _terrible_ experiences with Hackney releases being bad. First, I'm reaching out to community members to check if there's any immediate bugs that would prevent us from supporting it. Assuming I don't hear anything, I will add support for it.

**Comment by cuongtnx** [comment]
Sorry my mistake, they actually do a number of updates on that version (taken from the doc)

 - security: certifi 2.0.0
 - dependency: update idna 5.1.0 (fix windows build and usage with elixir)
 - doc: fix typo hackney_multipart doc (#422)

I'm waiting on Timber's update on this issue. Thanks, David.

**Comment by AndrewDryga** [comment]
+1 for update

**Comment by binarylogic** [comment]
@cuongtnx @AndrewDryga I just merged this into master. Once the build and tests complete I'll release an update. Thanks for your patience on this! We wanted to ensure 1.9 was stable before introducing it in our library.

**Comment by binarylogic** [comment]
Version `2.5.3` has been released. Let us know if you need anything else.
