### ISSUE TITLE
removal of HTTP client events

### ISSUE THREAD

**Issue by doughsay** [timberio/timber-elixir#212]
I'm wondering why the HTTP client events were removed in commit 826db4cba6fc269771e070672d68ea15ec3dc5d4.

I was using those in [maxwell_timber](https://github.com/doughsay/maxwell_timber) to capture outgoing http requests from inside the application.  From what I understand, these were the correct events to use, since the existing HTTP events are meant for *incoming* requests to the application, not *outgoing*.  Am I supposed to just start using custom events for this now?

**Comment by binarylogic** [comment]
Hey @doughsay, I should have explained that better in the `2.4.0` release, my apologies for the confusion. We simplified this to use the [`HTTPRequestEvent`](https://github.com/timberio/timber-elixir/blob/master/lib/timber/events/http_request_event.ex) and [`HTTPResponseEvent`](https://github.com/timberio/timber-elixir/blob/master/lib/timber/events/http_response_event.ex). There is a `direction` attribute on those events that can be `incoming` or `outgoing`. The direction is from the perspective of the application. So incoming http requests (requests to your application from your users) can be logged like:

```elixir
Logger.info fn ->
  event = %HTTPRequestEvent.new(direction: "incoming" ...}
  message = HTTPRequestEvent.message(event)
  {message, event: event}
end
```

We had a number of users confused with the HTTP event terminology. And really they're all just HTTP requests, so we felt it simpler to make this change. Let me know if you disagree we can open the discussion back up.

Also, this should have been a major bump, I'm going to create a new release that adds back the deprecated structs. We will remove them in `3.X`.

Let me know if that explains it.

**Comment by binarylogic** [comment]
Oh, and we recently added this docs page: https://timber.io/docs/languages/elixir/usage/track-external-service-communication

This demonstrates how we track external communication internally with our own services.

**Comment by doughsay** [comment]
Thanks for explaining!  I'll update maxwell_timber accordingly; It's fine about the non-major bump from my perspective, my lib isn't even at 1.0 anyway, so it's not expected to be that stable right now anyway.
