### ISSUE TITLE
User reports duplication of Endpoint plug series after multiple install runs

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#221]
A user reported that the follow block (injected into the Endpoint by the install script) was present multiple times in his Endpoint after multiple install runs:

```elixir
# Add Timber plugs for capturing HTTP context and events
plug Timber.Integrations.SessionContextPlug
plug Timber.Integrations.HTTPContextPlug
plug Timber.Integrations.EventPlug
```

It seems that the find-and-replace identification may be over zealous.

This particularly results in the response log being generated multiple times since `EventPlug` will queue a response log for each time it is called.

**Comment by mitchellhenke** [comment]
@DavidAntaramian @binarylogic do you know which version of Phoenix/Timber this happened in?  I wasn't able to replicate on Phoenix 1.3/Timber 2.8.2

**Comment by DavidAntaramian** [comment]
@mitchellhenke I do not, but the date it was filed suggests that it would have probably been a Timber 2.5.x version.

**Comment by mitchellhenke** [comment]
@DavidAntaramian safe to close then? 🙂

**Comment by DavidAntaramian** [comment]
I think so; if someone else encounters this error, they should open a new issue
