### ISSUE TITLE
Phoenix Instrumentation attempts to check MapSet membership on a list

### ISSUE THREAD

**Issue by nsweeting** [timberio/timber-elixir#232]
Hi there,

I'm currently getting the following error with my controllers:

`Instrumenter Timber.Integrations.PhoenixInstrumenter.phoenix_controller_call/3 failed. ** (FunctionClauseError) no function clause matching in MapSet.member?/ (elixir) lib/map_set.ex:259: MapSet.member?([], {MyApp.API.V1.PingController, :show}) lib/timber/integrations/phoenix_instrumenter.ex:293: Timber.Integrations.PhoenixInstrumenter.phoenix_controller_call/3 (my_app_api) lib/my_app/endpoint.ex:1: MyApp.API.Endpoint.instrument/4 (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1 (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4 (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1 (my_app_api) lib/my_app_api/endpoint.ex:1: MyApp.API.Endpoint.plug_builder_call/2 (my_app_api) lib/plug/debugger.ex:99: MyApp.API.Endpoint."call (overridable 3)"/2 (my_app_api) lib/my_app_api/endpoint.ex:1: MyApp.API.Endpoint.call/2 (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/ (cowboy) /home/name/Documents/umbrella/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4`

Running Phoenix 1.3, under an umbrella app. with a main router that forwards to "versioned" routers.

**Comment by DavidAntaramian** [comment]
@nsweeting Thanks for reporting this. I'm looking into it!

**Comment by DavidAntaramian** [comment]
Issues seems to be that [`Timber.Integrations.PhoenixInstrumenter.get_parsed_list/0`](https://github.com/timberio/timber-elixir/blob/v2.5.5/lib/timber/integrations/phoenix_instrumenter.ex#L163) is returning an empty list (`[]`) instead of an empty MapSet as a default.

**Comment by DavidAntaramian** [comment]
Fixing this, but as an FYI, this should not cause production issues since the instrumentation calls are protected from failures at runtime by the Phoenix code

**Comment by nsweeting** [comment]
Yeah - the error never actually showed up in local logs. It was showing up in timber though.
