### ISSUE TITLE
Implement optional clear sequence ANSI formatting

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#24]
In the ruby gem we offer an option to completely hide the context using ANSI formatting. The idea is to pre-prend the context and apply a "clear sequence" every 20 characters. This is somewhat hacky, but offers the option to tail your logs in the console without the context appearing.

The clear sequence formatting codes are: `\e8\e[K`. This moves the cursor to the beginning of the line and hides any current contents. Again, this requires the context to be prepended with a `@original` callout that signals the start of the original line.

**Comment by DavidAntaramian** [comment]
Theres currently a conceal option which makes the context invisible when tailing. I'd need to check the exact ANSI code it is using

**Comment by binarylogic** [comment]
Yep, I noticed that, but it doesn't completely hide the context, it just blanks it out. It's similar to `visibility:hidden` in CSS, where what I'm describing is more like `display:none`.

**Comment by binarylogic** [comment]
I'll also add this might be too hacky for some people's taste and should be a preference. I'll defer to you on a reasonable default that you think is most inline with Elixir community values.

**Comment by DavidAntaramian** [comment]
Gotcha. That's easy to switch out, as long as it doesnt required modification of the context JSON data. The way that's structured it would be difficult to modify the internals.

**Comment by binarylogic** [comment]
It doesn't, it just changes the sequence. An example:

```
@timber.io <context json with clear sequence every 20 chars> @original<clear sequence> this is my raw log line
```

Happy to explain further. Also open to suggestions.

**Comment by DavidAntaramian** [comment]
The problem is this: `<context json with clear sequence every 20 chars>`

I can _wrap_ the context JSON in anything, but modifying its internals (like putting a sequence every 20 characters) is dicey if not impossible because it's stored as an IO list.

I'll look at this more and see if there's a solution that better addresses what you're looking for but that can be implemented with the data structure.

**Comment by binarylogic** [comment]
Yep it's hacky for sure. If it's not possible then let's close. With ruby I convert the context to a JSON encoded string and then step through and insert the clear sequence.
