### ISSUE TITLE
Timber.Events.HTTPRequestEvent.message/1 does not coerce method field value to IO-data compatible term

### ISSUE THREAD

**Issue by sysashi** [timberio/timber-elixir#243]
Elixir version `1.5.1`
Timber version `2.6.1`

If I try to run an example from [Elixir Usage - Track External Service Communication](https://timber.io/docs/languages/elixir/usage/track-external-service-communication) it will raise with `no function clause matching in Logger.Utils.truncate_n/2`

Simplest way to reproduce in iex:
```
> require Logger
> event = Timber.Events.HTTPRequestEvent.new(method: :get, service_name: "Dummy")
> Logger.info(fn -> {Timber.Events.HTTPRequestEvent.message(event), [event: event]} end)
```

**Comment by DavidAntaramian** [comment]
@sysashi Please try changing the `method` value to a string for now.

**Comment by DavidAntaramian** [comment]
Actually, I was wrong in my initial evaluation. It looks like the problem is actually a `nil` term

**Comment by DavidAntaramian** [comment]
OK, so a few notes:

  1. The Logger macros have only allowed functions with two-tuple returns since 1.4, so this will fail on Elixir 1.3 and prior regardless of the library
  2. This is definitely an issue with the URL in the example given being set to `nil` by default.

The full stacktrace of the issue:

```
** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2    
    
    The following arguments were given to Logger.Utils.truncate_n/2:
    
        # 1
        nil
    
        # 2
        8083
    
    (logger) lib/logger/utils.ex:20: Logger.Utils.truncate_n/2
    (logger) lib/logger/utils.ex:49: Logger.Utils.truncate_n_list/3
    (logger) lib/logger/utils.ex:16: Logger.Utils.truncate/2
    (logger) lib/logger.ex:581: Logger.bare_log/3
```

**Comment by DavidAntaramian** [comment]
On 1.3 this can be replicated with a slight variation in IEx:

```elixir
require Logger
event = Timber.Events.HTTPRequestEvent.new(method: :get, service_name: "Dummy")
Logger.info(Timber.Events.HTTPRequestEvent.message(event), [event: event])
```

**Comment by DavidAntaramian** [comment]
@sysashi To clarify, are you seeing this anywhere besides testing with IEx? The problem in your example is that you don't have a URL parameter set, which result in a literal `nil` appearing in the chardata we prepare. I don't know of any situation where you would use this event without having the URL.

**Comment by sysashi** [comment]
@DavidAntaramian Thanks for the information :) 
Initially I added it in my code, and I don't really have a control over url I'm sending request to (I'm using a library and it's not really good in that sense), and since I in docs it says 

> Note: Only method is required for HTTPRequestEvent

I was adding only `method`, `direction` and `service_name` params. If I omit service_name everything works fine
