### ISSUE TITLE
Installer does not detect appropriate web.ex file for Phoenix 1.3

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#248]
Steps to reproduce:

1. `mix phx.new rabid_canary --no-brunch --no-ecto --no-html`
2. Add `{:timber, "~> 2.6.1"}`, to the `mix.exs` file
3. Run `mix deps.get && mix timber.install API_KEY` with a valid API key

Expected:

Installer finds `lib/rabid_canary_web.ex` and uses that as the web macro file.

Actual:

Installer reports:

```
We couldn't find a 'web.ex' file.

We need this to disable the default Phoenix controller logging

If you prefer, you can skip this and manually install later following
these instructions: https://timber.io/docs/languages/elixir/installation/manual

Please enter the correct relative path for the 'web.ex' file (or type 'skip' to skip):
```

This is a usability issue but not a breaking bug

**Comment by girishramnani** [comment]
This can be solved by changing the `PathHelper.find(["web","web.ex"],...)` to `PathHelper.find(["{lib,web}","*web.ex"],...)` . I will be happy to open a PR.

**Comment by girishramnani** [comment]
this issue was solved by https://github.com/timberio/timber-elixir/pull/254
