### ISSUE TITLE
Capture and log exceptions

### ISSUE THREAD

**Issue by tlvenn** [timberio/timber-elixir#260]
It does not seem like the integration with beam is capturing any errors at the moment. It would be nice to do so.

Something similar to this would be needed:
> https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/logger.ex

**Comment by binarylogic** [comment]
@tlvenn thanks for reporting. We have a similar issue open (https://github.com/timberio/timber-elixir/issues/94), so I'm going to close this in favor of that.

That said, we should be capturing every exception. If `handle_sasl_reports` and `handle_otp_reports` is enabled on the [`Logger` configuration](https://hexdocs.pm/logger/Logger.html#module-error-logger-configuration) we'll get the messages, but they will not be structured into a proper Exception event.

Finally, we're working with the same team that Sentry used to build out it's library, and we will have proper exception capturing and handling available sometime in April.
