### ISSUE TITLE
Test compatibility of Timber Elixir with OTP 21, Elixir 1.6.6+, and Elixir 1.7+

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#287]
This issue is actually about more than just testing compatibility, it's also about determine the best path forward for continuing to support users on Erlang/OTP installs below 21 and Elixir builds below 1.7 while still allowing users on OTP 21+ and the eventual Elixir 1.7+ to take advantage of new features for logging.

**Comment by binarylogic** [comment]
I'd also add that the `.travis.yml` file should be updated accordingly as well. If possible we should always be testing against the latest version.

**Comment by DavidAntaramian** [comment]
I'm going to close this now that we've determined the direction of the package and started formalizing the 3.0 move.
