### ISSUE TITLE
Verify new timber schema adherence

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#305]
The Timber Elixir library needs to be verified against the new library specification [adherence checklist](https://github.com/timberio/library-specification/blob/master/templates/ADHERENCE.template.md). This includes:

- [x] Copying the [adherence checklist](https://github.com/timberio/library-specification/blob/master/templates/ADHERENCE.template.md) into the Elixir repository.
- [x] Checking off the items that the library adheres to.
- [x] Opening issues for requirements the library fails to meet.

**Comment by DavidAntaramian** [comment]
https://github.com/timberio/timber-elixir/blob/prepare-3.x-line/ADHERENCE.md

**Comment by DavidAntaramian** [comment]
Relevant work to be done for adherence:

- #102 
- #213 
- #304
- #306 
- #307 
- #308 
- #309
