### ISSUE TITLE
Support Ecto 3.0

### ISSUE THREAD

**Issue by axelson** [timberio/timber-elixir#310]
Now that Ecto 3.0 is out it would be great if Timber supported it. I think the changes are fairly minimal from Timber's perspective.

**Comment by wcpines** [comment]
Any chance this was considered?

**Comment by mitchellhenke** [comment]
Ecto 3.0 is supported with Timber 3.0 and the most recent version of the Ecto integration library here: https://github.com/timberio/timber-elixir-ecto 🙂
