### ISSUE TITLE
Support Phoenix 1.4

### ISSUE THREAD

**Issue by rhnonose** [timberio/timber-elixir#311]
Can't update to phoenix 1.4:
```
Failed to use "phoenix" because
  apps/re_web/mix.exs requires ~> 1.4
  timber (versions 2.8.0 to 2.8.4) requires >= 1.2.0 and < 1.4.0 *
```

Overriding the dependency doesn't work

Not sure if there's any breaking changes but would be nice to be able to upgrade.

**Comment by Wijnand** [comment]
Any update? For us it is becoming a blocker and we are basically forced to move away from timber in the next couple of weeks

**Comment by mitchellhenke** [comment]
Phoenix 1.4 is supported with Timber 3.0 and the most recent version of the Plug and Phoenix integration libraries:
https://github.com/timberio/timber-elixir-plug
https://github.com/timberio/timber-elixir-phoenix
🙂
