### ISSUE TITLE
Proper handling for multiple repos

### ISSUE THREAD

**Issue by axelson** [timberio/timber-elixir#340]
Following the current upgrade and configuration docs I ran into an issue with an umbrella application that I maintain that has multiple Ecto Repo's. Since the `handler_id` passed into telemetry is not unique per repo there is a conflict and `:telemetry.attach/4` returns `{:error, :already_exists}`.

Is it safe to change the handler id or does timber expect specifically `"timber-ecto-query-handler"`?

**Comment by axelson** [comment]
Hmmm, maybe I should've posted this on https://github.com/timberio/timber-elixir-ecto, well at least I think you can now transfer issues between repos

**Comment by binarylogic** [comment]
Hey @axelson, great question. You should be able to rename `timber-ecto-query-handler` to whatever you like. I would align it with your repo names. That should fix your issue.
