### ISSUE TITLE
401 when calling Timber

### ISSUE THREAD

**Issue by zdeneksejcek** [timberio/timber-elixir#343]
Hi,

I use timber 3.1 and receive

```
We received a 401 response from the Timber API:
"The provided authorization token did not decode properly. This happens for 1 of 2 reasons, either the token is not base 64 encoded, or you specified the wrong strategy in the Authorization header. New API keys should use the \"Bearer\" strategy, not the \"Basic\" strategy."
```
for all requests including "test the pipes". Configuration seems ok to me.

Thanks.

**Comment by zdeneksejcek** [comment]
Master works well, but 3.1 is broken. Please release new version to hex. Thanks.

**Comment by binarylogic** [comment]
Hi @zdeneksejcek, thanks for letting us know. I believe we resolved this over support, but we released a new version which resolves this.

Please let us know if you find anything else.
