### ISSUE TITLE
Handle Poison encoding errors better

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-elixir#62]
If you try to log an event that contains data that cannot be encoded by json (ex: tuples), we need to be thoughtful around that. Users should not be doing this, but in the event it does happen an error better than the generic Poison error would be helpful.

**Comment by DavidAntaramian** [comment]
Encode errors look something like this:

```
%Poison.EncodeError{message: nil, value: {"is invalid", [validation: :inclusion]}}
```
