### ISSUE TITLE
Support Environment Variables at Runtime

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/timber-elixir#92]
Currently our system requires setting the API key in the application configuration as a binary. For customers sending logs from multiple environments using releases, it's not ideal to require the configuration value to be present at compile time. Therefore, we should support tuple based configuration of this value, such as `{:system, "TIMBER_API_KEY"}`

- Based on customer feedback

**Comment by binarylogic** [comment]
@DavidAntaramian this is done if you want to let them know.
